# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "elena-app"
client_id = "c16ad0d29fb9b06d1ddbf23b8bf3e08e"
application_url = "https://refuse-ourselves-analog-cas.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://refuse-ourselves-analog-cas.trycloudflare.com/auth/callback",
  "https://refuse-ourselves-analog-cas.trycloudflare.com/auth/shopify/callback",
  "https://refuse-ourselves-analog-cas.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wishlist-hero.myshopify.com"
